name = "auth-service"
main = "index.js"
compatibility_date = "2025-11-08"

[[d1_databases]]
binding = "AUTH_DB"
database_name = "verification_d1"   # same database
database_id = "f727a3c3-121e-487b-934b-2c66b1abbf29"  # same ID

[vars]
JWT_SECRET = "supersecretkey"
ADMIN_EMAIL = "L4kushwaha@gmail.com"
ADMIN_PASSWORD = "ELEGENT1832"
ADMIN_NAME = "Admin"
ADMIN_PHONE = "7905584212"
